/**
 * Meeting Transcription Process
 *
 * PARADIGM: STREAMING (live meeting mode) ────────────────────────────────────
 * This module owns the real-time LLM loop for an active meeting. It is called
 * continuously while recording is in progress — NOT after it ends.
 *
 * FOCUS CONTEXT: OUT-OF-APP primarily.
 * Data comes from the native app's system audio (remote participants via
 * Zoom/Meet/Teams) and mic audio (local user), streamed via WebSocket.
 * The user is typically in another app while this runs.
 *
 * Trigger cadence:
 *   - Main loop: every 8s minimum (LLM_THROTTLE_MS), or when MIN_ACCUMULATED_CHARS
 *     is reached (80 chars), or after STALE_TEXT_TIMEOUT_MS silence (20s).
 *   - End-of-meeting: generateMeetingEndSummary() fires once after recording ends
 *     (the designated slot for post-meeting batch features: title, decisions, etc.)
 *
 * This module does NOT call processInput() / the core processor. It has its
 * own independent LLM prompt and state machine. Completed meeting data is
 * stored in WatermelonDB via widgetRecordStore, not the conversations table.
 *
 * GAP — INTEGRATION WITH WORKING MEMORY:
 *   Live meeting segments are never fed into WorkingMemory (which only reads
 *   the conversations DB). This means the core processor's entity/topic/memory
 *   extraction is not enriched by live meeting content in real time.
 *   Future: after a meeting ends, push the full transcript through processInput()
 *   so entities, topics, and memories get extracted and persist cross-session.
 * ─────────────────────────────────────────────────────────────────────────────
 *
 * State machine for live meeting transcription + LLM summarization.
 *
 * Intelligence layers:
 *   overviewItems → additive log, one bullet per significant moment, never deleted mid-meeting
 *   topic         → current major theme, full rewrite when discussion shifts
 *   now           → latest exchange, always updated
 *   actionItems   → tracked list of commitments/tasks extracted from conversation
 *   participants  → names inferred from conversation
 *   talkTime      → accumulated mic vs system audio duration (tracked in Widget)
 *   sentiment     → neutral / positive / tense / negative
 *
 * Overview delta approach:
 *   LLM outputs overallDelta: string | null — appended only when genuinely new/significant.
 *   Never rewrites old items. Compaction deferred to end-of-meeting if needed.
 *
 * Token budget (approximate input):
 *   overview (12 items × 120 chars)   =  1 440
 *   topic 400 + now 200               =    600
 *   action items (10 × 120)           =  1 200
 *   history (8 × 400)                 =  3 200
 *   new content                       =    600
 *   overhead                          =    400
 *   ──────────────────────────────────────────
 *   total                     ~7 440 chars ≈ ~1 860 tokens input
 */

import { z } from 'zod';
import { callLLM } from '../../../program/llmClient';
import { parseLLMJSON } from '../../../program/utils/jsonUtils';
import { profileStorage } from '../../../lib/profileStorage';
import { widgetRecordStore } from '../../../db/stores';

// ============================================================================
// Constants
// ============================================================================

// Settings stay in profileStorage — they are user preferences, not LLM-generated data
export const SETTINGS_STORAGE_KEY = 'meeting-transcription:settings';

// WatermelonDB widget type / subtype constants
const MEETING_WIDGET_TYPE = 'meeting';
const MEETING_SUBTYPE_ACTIVE = 'active';
const MEETING_SUBTYPE_ARCHIVE = 'archive';

/** Min chars accumulated since last LLM call before we bother calling again */
export const MIN_ACCUMULATED_CHARS = 80;

/** After this ms of silence, fire LLM even if accumulated text is short */
export const STALE_TEXT_TIMEOUT_MS = 20_000;

const LLM_THROTTLE_MS = 8_000;
const MAX_HISTORY = 20;
const MAX_ARCHIVE = 50;
const LLM_HISTORY_WINDOW = 8;
const MAX_OVERVIEW_ITEMS_IN_PROMPT = 12;
const MAX_ACTION_ITEMS = 20;

/** Gap in ms after which a new recording-started is treated as a new meeting */
export const NEW_MEETING_GAP_MS = 3 * 60 * 1000;

// LLM input caps
const MAX_OVERVIEW_ITEM_CHARS = 120;
const MAX_TOPIC_CHARS         = 400;
const MAX_NOW_CHARS           = 200;
const MAX_ACTION_ITEM_CHARS   = 120;
const MAX_HISTORY_SEGMENT_CHARS = 400;
const MAX_ACCUMULATED_TEXT_CHARS = 600;

// ============================================================================
// Types
// ============================================================================

export interface SummaryLevel {
  text: string;
  /** Iconify icon name generated by LLM, e.g. "mdi:target" */
  icon: string;
  updatedAt: number;
}

export interface SummaryTree {
  /** Mirrors the latest overviewItem text — kept for archive/display compat */
  overall: SummaryLevel;
  /** Current major topic / phase. Full rewrite when discussion shifts. */
  topic: SummaryLevel;
  /** Latest exchange right now. Always updated. */
  now: SummaryLevel;
}

/** One bullet in the additive overview log. Appended, never deleted mid-meeting. */
export interface OverviewItem {
  text: string;
  ts: number;
}

export interface ActionItem {
  id: string;
  text: string;
  /** Inferred owner — participant name, "you", or undefined if unknown */
  owner?: string;
  /** Inferred deadline if mentioned, e.g. "by Friday" */
  deadline?: string;
  ts: number;
  done: boolean;
}

/** 'tense' = rising conflict/disagreement; 'negative' = clear frustration/anger */
export type SentimentLevel = 'neutral' | 'positive' | 'tense' | 'negative';

export interface Participant {
  name: string;
  audioType: 'mic' | 'system';
  firstSeenAt: number;
}

export interface TalkTime {
  micMs: number;
  systemMs: number;
}

export interface FeedEntry {
  id: string;
  text: string;
  audioType: 'mic' | 'system';
  ts: number;
}

export interface HistorySegment {
  text: string;
  audioType: 'mic' | 'system';
  ts: number;
}

export interface MeetingSettings {
  userName: string;
  meetingContext: string;
}

export interface MeetingState {
  displayFeed: FeedEntry[];
  /** Complete transcript — never truncated (cap 2000). Used for archiving & export. */
  fullFeed: FeedEntry[];
  history: HistorySegment[];
  summaryTree: SummaryTree;
  overviewItems: OverviewItem[];
  actionItems: ActionItem[];
  participants: Participant[];
  talkTime: TalkTime;
  sentiment: SentimentLevel;
  lastLLMCallAt: number;
  lastUpdatedAt: number;
  llmDurationMs: number;
  segmentCount: number;
  startedAt: number;
  /** Auto-generated meeting title (produced by end-of-meeting LLM call) */
  title: string;
  /** Detailed end-of-meeting summary — decisions, outcomes, key discussion points */
  summary: string;
}

export interface ArchivedMeeting {
  id: string;
  startedAt: number;
  endedAt: number;
  summaryTree: SummaryTree;
  overviewItems: OverviewItem[];
  actionItems: ActionItem[];
  participants: Participant[];
  talkTime: TalkTime;
  displayFeed: FeedEntry[];
  /** Complete transcript — never truncated (cap 2000). Used for export. */
  fullFeed: FeedEntry[];
  history: HistorySegment[];
  segmentCount: number;
  /** Auto-generated meeting title (produced by end-of-meeting LLM call) */
  title: string;
  /** Detailed end-of-meeting summary — decisions, outcomes, key discussion points */
  summary: string;
}

export interface MeetingUpdateResult {
  state: MeetingState;
  llmRan: boolean;
}

// ============================================================================
// Zod schemas
// ============================================================================

const SummaryLevelSchema = z.object({
  text: z.string(),
  icon: z.string(),
  updatedAt: z.number(),
});

const SummaryTreeSchema = z.object({
  overall: SummaryLevelSchema,
  topic: SummaryLevelSchema,
  now: SummaryLevelSchema,
});

const FeedEntrySchema = z.object({
  id: z.string(),
  text: z.string(),
  audioType: z.enum(['mic', 'system']),
  ts: z.number(),
});

const HistorySegmentSchema = z.object({
  text: z.string(),
  audioType: z.enum(['mic', 'system']),
  ts: z.number(),
});

const OverviewItemSchema = z.object({
  text: z.string(),
  ts: z.number(),
});

const ActionItemSchema = z.object({
  id: z.string(),
  text: z.string(),
  owner: z.string().optional(),
  deadline: z.string().optional(),
  ts: z.number(),
  done: z.boolean(),
});

const ParticipantSchema = z.object({
  name: z.string(),
  audioType: z.enum(['mic', 'system']),
  firstSeenAt: z.number(),
});

const TalkTimeSchema = z.object({
  micMs: z.number(),
  systemMs: z.number(),
});

const SentimentLevelSchema = z.enum(['neutral', 'positive', 'tense', 'negative']);

const MeetingStateSchema = z.object({
  displayFeed: z.array(FeedEntrySchema),
  fullFeed: z.array(FeedEntrySchema).default([]),
  history: z.array(HistorySegmentSchema),
  summaryTree: SummaryTreeSchema,
  overviewItems: z.array(OverviewItemSchema),
  actionItems: z.array(ActionItemSchema),
  participants: z.array(ParticipantSchema),
  talkTime: TalkTimeSchema,
  sentiment: SentimentLevelSchema,
  lastLLMCallAt: z.number(),
  lastUpdatedAt: z.number(),
  llmDurationMs: z.number(),
  segmentCount: z.number(),
  startedAt: z.number(),
  // default('') so existing stored data without this field migrates instead of being wiped
  title: z.string().default(''),
  summary: z.string().default(''),
});

const ArchivedMeetingSchema = z.object({
  id: z.string(),
  startedAt: z.number(),
  endedAt: z.number(),
  summaryTree: SummaryTreeSchema,
  overviewItems: z.array(OverviewItemSchema),
  actionItems: z.array(ActionItemSchema),
  participants: z.array(ParticipantSchema),
  talkTime: TalkTimeSchema,
  displayFeed: z.array(FeedEntrySchema),
  fullFeed: z.array(FeedEntrySchema).default([]),
  history: z.array(HistorySegmentSchema),
  segmentCount: z.number(),
  // default('') so existing archived meetings without this field migrate instead of being wiped
  title: z.string().default(''),
  summary: z.string().default(''),
});

const MeetingSettingsSchema = z.object({
  userName: z.string(),
  meetingContext: z.string(),
});

// ============================================================================
// Storage — meeting state + archive → WatermelonDB; settings → profileStorage
// ============================================================================

/**
 * Save active meeting state (fire-and-forget upsert — never throws).
 * Keeps sync signature so Widget.tsx call sites don't need to change.
 */
export function saveMeetingState(state: MeetingState): void {
  widgetRecordStore.upsert(MEETING_WIDGET_TYPE, MEETING_SUBTYPE_ACTIVE, {
    content: state,
    title: state.title || 'Active Meeting',
  }).catch(e => console.warn('[MeetingTranscription] Failed to save state:', e));
}

/**
 * Load active meeting state from WatermelonDB with Zod validation.
 */
export async function loadMeetingState(): Promise<MeetingState | null> {
  try {
    // Check how many active records exist (should be 0 or 1)
    const allActive = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, 100, MEETING_SUBTYPE_ACTIVE);
    console.log('[Load] active records in DB:', allActive.length);

    const record = allActive[0] ?? null;
    if (!record) return null;

    const result = MeetingStateSchema.safeParse(record.contentParsed);
    if (!result.success) {
      console.warn('[MeetingTranscription] State schema changed — resetting:', result.error.issues);
      return null;
    }
    console.log('[Load] loaded active state — segments:', result.data.segmentCount, 'startedAt:', result.data.startedAt);
    return result.data;
  } catch (error) {
    console.warn('[MeetingTranscription] Failed to load state:', error);
    return null;
  }
}

/**
 * Clear the active meeting state (fire-and-forget — never throws).
 */
export function clearMeetingState(): void {
  widgetRecordStore.getLatest(MEETING_WIDGET_TYPE, MEETING_SUBTYPE_ACTIVE)
    .then(record => record ? widgetRecordStore.delete(record.id) : undefined)
    .catch(e => console.warn('[MeetingTranscription] Failed to clear state:', e));
}

/**
 * Load archived meetings from WatermelonDB (up to MAX_ARCHIVE, most recent first).
 */
export async function loadArchivedMeetings(): Promise<ArchivedMeeting[]> {
  try {
    const rows = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, MAX_ARCHIVE, MEETING_SUBTYPE_ARCHIVE);
    const seen = new Set<string>();
    const meetings: ArchivedMeeting[] = [];
    for (const row of rows) {
      const result = ArchivedMeetingSchema.safeParse(row.contentParsed);
      if (result.success && !seen.has(result.data.id)) {
        seen.add(result.data.id);
        meetings.push(result.data);
      }
    }
    return meetings;
  } catch {
    return [];
  }
}

/**
 * Archive the current meeting.
 * Transitions the active row to 'archive' subtype (or creates a new archive row if missing).
 * Returns the updated list of archived meetings.
 */
export async function archiveCurrentMeeting(state: MeetingState): Promise<ArchivedMeeting[]> {
  if (state.segmentCount === 0) return loadArchivedMeetings();

  const archived: ArchivedMeeting = {
    id: `meeting-${state.startedAt}`,
    startedAt: state.startedAt,
    endedAt: Date.now(),
    summaryTree: state.summaryTree,
    overviewItems: state.overviewItems,
    actionItems: state.actionItems,
    participants: state.participants,
    talkTime: state.talkTime,
    displayFeed: state.displayFeed,
    fullFeed: state.fullFeed,
    history: state.history,
    segmentCount: state.segmentCount,
    title: state.title,
    summary: state.summary,
  };

  // Get ALL active records — fire-and-forget saveMeetingState can create duplicates
  // via the non-atomic upsert race. We must transition/clean ALL of them.
  const allActive = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, 100, MEETING_SUBTYPE_ACTIVE);
  console.log('[Archive] active records found:', allActive.length);

  if (allActive.length > 0) {
    // Transition the first (latest) to archive with the meeting data
    await widgetRecordStore.update(allActive[0].id, {
      content: archived,
      subtype: MEETING_SUBTYPE_ARCHIVE,
      title: archived.title || undefined,
    });
    // Delete any stale duplicate active records
    for (let i = 1; i < allActive.length; i++) {
      console.log('[Archive] deleting stale active record:', allActive[i].id);
      await widgetRecordStore.delete(allActive[i].id);
    }
  } else {
    // No active row exists — create a new archive row directly
    await widgetRecordStore.create({
      type: MEETING_WIDGET_TYPE,
      subtype: MEETING_SUBTYPE_ARCHIVE,
      content: archived,
      title: archived.title || undefined,
      createdAt: archived.startedAt,
    });
  }

  return loadArchivedMeetings();
}

/**
 * Patch the title of an already-archived meeting by id.
 * Called after the end-of-meeting LLM title generation — archive was already saved.
 */
export async function updateArchivedMeetingTitle(meetingId: string, title: string): Promise<ArchivedMeeting[]> {
  // Find the archive row whose content has the matching id
  const rows = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, MAX_ARCHIVE, MEETING_SUBTYPE_ARCHIVE);
  for (const row of rows) {
    const parsed = ArchivedMeetingSchema.safeParse(row.contentParsed);
    if (parsed.success && parsed.data.id === meetingId) {
      await widgetRecordStore.update(row.id, {
        content: { ...parsed.data, title },
        title,
      });
      break;
    }
  }
  return loadArchivedMeetings();
}

export function loadMeetingSettings(): MeetingSettings {
  try {
    const raw = profileStorage.getJSON<unknown>(SETTINGS_STORAGE_KEY);
    if (raw == null) return { userName: '', meetingContext: '' };
    const result = MeetingSettingsSchema.safeParse(raw);
    return result.success ? result.data : { userName: '', meetingContext: '' };
  } catch {
    return { userName: '', meetingContext: '' };
  }
}

export function saveMeetingSettings(settings: MeetingSettings): void {
  try {
    profileStorage.setJSON(SETTINGS_STORAGE_KEY, settings);
  } catch (error) {
    console.warn('[MeetingTranscription] Failed to save settings:', error);
  }
}

// ============================================================================
// Initial state
// ============================================================================

export function createInitialMeetingState(): MeetingState {
  return {
    displayFeed: [],
    fullFeed: [],
    history: [],
    summaryTree: {
      overall: { text: '', icon: 'mdi:flag-outline', updatedAt: 0 },
      topic:   { text: '', icon: 'mdi:comment-multiple-outline', updatedAt: 0 },
      now:     { text: '', icon: 'mdi:lightning-bolt-outline', updatedAt: 0 },
    },
    overviewItems: [],
    actionItems: [],
    participants: [],
    talkTime: { micMs: 0, systemMs: 0 },
    sentiment: 'neutral',
    lastLLMCallAt: 0,
    lastUpdatedAt: Date.now(),
    llmDurationMs: 0,
    segmentCount: 0,
    startedAt: Date.now(),
    title: '',
    summary: '',
  };
}

// ============================================================================
// LLM Prompts
// ============================================================================

function buildSystemPrompt(): string {
  return `You are a live meeting intelligence assistant.

━━━ INPUT SOURCE ━━━
Input is raw speech-to-text transcription — it may contain recognition errors or mispronunciations.
Use surrounding context to infer intended meaning. Do not autocorrect unless highly confident.

━━━ AUDIO CHANNELS ━━━
• "mic"    = you (the local user) — see MIC USER in the user message
• "system" = remote participants — one or more people, audio routed through Teams / Zoom / Meet / etc.
             If a name is clearly audible (e.g. "Hi, I'm Sarah"), note them as a participant.

ECHO / BLEED WARNING:
Without headphones, system audio plays through speakers and is picked up by the mic — so the same
speech may appear as both "system" and "mic" in close succession. If a "mic" segment is nearly
identical in content to a recent "system" segment, treat it as echo/bleed — do NOT attribute it
to the local user.

━━━ VOICE STYLE ━━━
Compact, never paraphrase into 3rd-person narrative.
✗ WRONG: "The team discussed budget concerns"
✓ RIGHT:  "Budget tight — can't fund both projects this quarter"
Preserve first-person voice: keep "I think", "We need", "Let's" intact.

━━━ OVERVIEW (additive bullet log) ━━━
The overview is an immutable log of the whole meeting — bullets are NEVER rewritten or removed.
• Output overallDelta ONLY when the new content contains something genuinely significant:
  a new decision, commitment, goal, key fact, or clear topic shift.
• If it is continuation, small-talk, repetition, or elaboration of an existing bullet — output null.
• One short phrase, max 15 words. First-person voice.
• You are APPENDING a new bullet, not rewriting anything.

━━━ TOPIC ━━━
Current major theme. Fully rewrite when discussion clearly shifts. Max 50 words.

━━━ NOW ━━━
Most recent exchange — what is being said right now. Always update. Max 30 words.

━━━ ACTION ITEMS ━━━
Extract explicit or strongly implied tasks/commitments from the NEW content only.
Return only NEW items — do not re-list existing ones. Empty array if none.

Only extract items that are clearly assignable, concrete, and would stand alone in formal meeting notes. Skip vague fragments and rhetorical statements.

Before adding a new item, check the OPEN ACTION ITEMS list: if the new item substantially duplicates
an existing open item (same task, even if phrased differently), skip it — do not add a duplicate.
Each: short text, optional owner ("you" for mic-user, participant name, or omit), optional deadline.

━━━ SENTIMENT ━━━
Overall mood right now:
  "neutral"  = ordinary discussion
  "positive" = enthusiasm, agreement, good energy
  "tense"    = disagreement, friction, raised stakes
  "negative" = clear frustration or conflict

━━━ PARTICIPANTS ━━━
If a name is clearly introduced in the new content, return them. Empty array otherwise.

━━━ RESPONSE FORMAT (strict JSON, no markdown) ━━━
{
  "overallDelta": "short phrase" | null,
  "overallIcon": "mdi:... (only when overallDelta is non-null)",
  "topic":  { "text": "...", "icon": "mdi:..." },
  "now":    { "text": "...", "icon": "mdi:..." },
  "actionItems": [{ "text": "...", "owner": "..." | null, "deadline": "..." | null }],
  "sentiment": "neutral" | "positive" | "tense" | "negative",
  "newParticipants": [{ "name": "...", "audioType": "mic" | "system" }]
}`;
}

function truncate(text: string, max: number): string {
  if (text.length <= max) return text;
  return text.slice(0, max) + '…';
}

function buildUserPrompt(
  state: MeetingState,
  accumulatedText: string,
  latestAudioType: 'mic' | 'system',
  settings: MeetingSettings
): string {
  const { summaryTree: tree } = state;

  const micUser = settings.userName || 'the local user';
  const contextHeader = settings.meetingContext
    ? `MIC USER: ${micUser}\nMEETING CONTEXT: ${settings.meetingContext}\n\n`
    : `MIC USER: ${micUser}\n\n`;

  const overviewBlock = state.overviewItems.length === 0
    ? '(meeting just started — no overview items yet)'
    : state.overviewItems
        .slice(-MAX_OVERVIEW_ITEMS_IN_PROMPT)
        .map((item, i) => `${i + 1}. ${truncate(item.text, MAX_OVERVIEW_ITEM_CHARS)}`)
        .join('\n');

  const topicText = tree.topic.text ? truncate(tree.topic.text, MAX_TOPIC_CHARS) : '(none yet)';
  const nowText   = tree.now.text   ? truncate(tree.now.text,   MAX_NOW_CHARS)   : '(nothing yet)';

  const openActions = state.actionItems.filter((a) => !a.done);
  const actionItemsBlock = openActions.length === 0
    ? '(none)'
    : openActions
        .slice(-10)
        .map((a) => {
          let line = `• ${truncate(a.text, MAX_ACTION_ITEM_CHARS)}`;
          if (a.owner) line += ` [${a.owner}]`;
          if (a.deadline) line += ` — ${a.deadline}`;
          return line;
        })
        .join('\n');

  const recentHistory = state.history
    .slice(-LLM_HISTORY_WINDOW)
    .map((s) => `[${s.audioType === 'mic' ? 'MIC' : 'SYSTEM'}] ${truncate(s.text, MAX_HISTORY_SEGMENT_CHARS)}`)
    .join('\n');

  const participantsLine = state.participants.length > 0
    ? `KNOWN PARTICIPANTS: ${state.participants.map((p) => `${p.name} (${p.audioType})`).join(', ')}\n\n`
    : '';

  // Appended last so the stable prefix above remains cacheable by the LLM API.
  const sessionTime = new Date().toISOString().slice(0, 16).replace('T', ' ') + ' UTC';

  return `${contextHeader}CURRENT OVERVIEW LOG:
${overviewBlock}

CURRENT TOPIC: ${topicText}
CURRENT NOW:   ${nowText}

OPEN ACTION ITEMS:
${actionItemsBlock}

${participantsLine}RECENT HISTORY:
${recentHistory || '(none yet)'}

NEW CONTENT [source: ${latestAudioType === 'mic' ? 'MIC' : 'SYSTEM'}]:
${truncate(accumulatedText, MAX_ACCUMULATED_TEXT_CHARS)}

<meta>current_time: ${sessionTime}</meta>`;
}

// ============================================================================
// State machine update
// ============================================================================

/**
 * Run an LLM update cycle with the text accumulated since the last call.
 *
 * Widget owns: displayFeed, segmentCount, talkTime, accumulation logic.
 * This function owns: summaryTree, overviewItems, actionItems, participants,
 *                     sentiment, history, lastLLMCallAt, llmDurationMs, storage.
 */
export async function processMeetingUpdate(
  state: MeetingState,
  accumulatedText: string,
  latestAudioType: 'mic' | 'system',
  settings: MeetingSettings,
  forceImmediate = false
): Promise<MeetingUpdateResult> {
  const now = Date.now();
  const timeSinceLast = now - state.lastLLMCallAt;

  if (!forceImmediate && timeSinceLast < LLM_THROTTLE_MS) {
    return { state, llmRan: false };
  }

  const startTime = performance.now();
  try {
    const response = await callLLM({
      tier: 'medium',
      prompt: buildUserPrompt(state, accumulatedText, latestAudioType, settings),
      systemPrompt: buildSystemPrompt(),
      options: { max_tokens: 900 },
    });

    const llmDurationMs = Math.round(performance.now() - startTime);
    const { data } = parseLLMJSON(response.content);

    let newOverviewItems = [...state.overviewItems];
    const newTree: SummaryTree = {
      overall: { ...state.summaryTree.overall },
      topic:   { ...state.summaryTree.topic },
      now:     { ...state.summaryTree.now },
    };
    let newActionItems = [...state.actionItems];
    let newParticipants = [...state.participants];
    let newSentiment: SentimentLevel = state.sentiment;

    if (data && typeof data === 'object') {
      const obj = data as Record<string, unknown>;

      // ── Overview: append delta only ──
      if (typeof obj.overallDelta === 'string' && obj.overallDelta.trim()) {
        const delta = obj.overallDelta.trim();
        newOverviewItems = [...newOverviewItems, { text: delta, ts: now }];
        const icon =
          typeof obj.overallIcon === 'string' && obj.overallIcon.includes(':')
            ? (obj.overallIcon as string)
            : newTree.overall.icon;
        newTree.overall = { text: delta, icon, updatedAt: now };
      }

      // ── Topic + Now: full rewrite ──
      for (const level of ['topic', 'now'] as const) {
        const raw = obj[level];
        if (raw && typeof raw === 'object') {
          const l = raw as Record<string, unknown>;
          if (typeof l.text === 'string' && l.text.trim()) {
            newTree[level] = {
              text: l.text.trim(),
              icon: typeof l.icon === 'string' && l.icon.includes(':') ? l.icon : newTree[level].icon,
              updatedAt: now,
            };
          }
        }
      }

      // ── Action items: append new ones ──
      const rawItems = obj.actionItems;
      if (Array.isArray(rawItems)) {
        for (const raw of rawItems) {
          if (raw && typeof raw === 'object') {
            const item = raw as Record<string, unknown>;
            if (typeof item.text === 'string' && item.text.trim()) {
              newActionItems = [
                ...newActionItems,
                {
                  id: `ai-${now}-${Math.random().toString(36).slice(2, 7)}`,
                  text: item.text.trim(),
                  owner: typeof item.owner === 'string' && item.owner.trim() ? item.owner.trim() : undefined,
                  deadline: typeof item.deadline === 'string' && item.deadline.trim() ? item.deadline.trim() : undefined,
                  ts: now,
                  done: false,
                },
              ];
            }
          }
        }
        if (newActionItems.length > MAX_ACTION_ITEMS) {
          newActionItems = newActionItems.slice(-MAX_ACTION_ITEMS);
        }
      }

      // ── Sentiment ──
      const s = obj.sentiment;
      if (s === 'neutral' || s === 'positive' || s === 'tense' || s === 'negative') {
        newSentiment = s;
      }

      // ── New participants: merge, no duplicates ──
      const rawParticipants = obj.newParticipants;
      if (Array.isArray(rawParticipants)) {
        for (const raw of rawParticipants) {
          if (raw && typeof raw === 'object') {
            const p = raw as Record<string, unknown>;
            if (typeof p.name === 'string' && p.name.trim()) {
              const name = p.name.trim();
              const audioType: 'mic' | 'system' = p.audioType === 'mic' ? 'mic' : 'system';
              if (!newParticipants.some((e) => e.name.toLowerCase() === name.toLowerCase())) {
                newParticipants = [...newParticipants, { name, audioType, firstSeenAt: now }];
              }
            }
          }
        }
      }
    }

    // ── History ──
    const historyEntry: HistorySegment = {
      text: truncate(accumulatedText, MAX_HISTORY_SEGMENT_CHARS),
      audioType: latestAudioType,
      ts: now,
    };
    const updatedHistory = [...state.history, historyEntry];
    if (updatedHistory.length > MAX_HISTORY) {
      updatedHistory.splice(0, updatedHistory.length - MAX_HISTORY);
    }

    const newState: MeetingState = {
      ...state,
      history: updatedHistory,
      summaryTree: newTree,
      overviewItems: newOverviewItems,
      actionItems: newActionItems,
      participants: newParticipants,
      sentiment: newSentiment,
      lastLLMCallAt: now,
      llmDurationMs,
    };

    saveMeetingState(newState);
    return { state: newState, llmRan: true };
  } catch (error) {
    console.error('[MeetingTranscription] LLM call failed:', error);
    return { state: { ...state, lastLLMCallAt: now }, llmRan: false };
  }
}

// ============================================================================
// End-of-meeting summary
//
// Single LLM call fired once when recording ends (after the final flush).
// This is the designated slot for ALL future end-of-meeting features.
// Currently generates: title.
// Future: decisions log, key numbers, follow-up email draft, etc.
// ============================================================================

/**
 * Generate end-of-meeting title + detailed summary.
 *
 * This is the ONE post-meeting LLM call. Uses medium tier — meeting is over,
 * latency doesn't matter, quality does. Receives full transcript + live
 * overview + action items and produces a thorough meeting record.
 *
 * The caller (Widget.tsx) handles persisting title + summary to the archive.
 */
export async function generateMeetingEndSummary(
  state: MeetingState,
  settings: MeetingSettings
): Promise<MeetingState> {
  if (state.segmentCount === 0) return state;

  // ── Assemble meeting context ──────────────────────────────────────────
  const meetingDate = new Date(state.startedAt);
  const dateStr = meetingDate.toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });
  const timeStr = meetingDate.toLocaleTimeString('en-US', {
    hour: '2-digit', minute: '2-digit',
  });
  const durationMin = Math.round((Date.now() - state.startedAt) / 60000);

  const overviewText = state.overviewItems.map((item, i) => {
    const itemTime = new Date(item.ts).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    return `${i + 1}. [${itemTime}] ${item.text}`;
  }).join('\n');

  const actionText = state.actionItems
    .map(a => `- ${a.done ? '[DONE] ' : ''}${a.text}${a.owner ? ` [${a.owner}]` : ''}${a.deadline ? ` — due: ${a.deadline}` : ''}`)
    .join('\n');

  const contextLine = settings.meetingContext ? `Meeting context: ${settings.meetingContext}\n` : '';
  const participantNames = state.participants.map(p => `${p.name} (${p.audioType})`).join(', ');

  // Build transcript with timestamps
  const transcript = state.fullFeed.length > 0 ? state.fullFeed : state.displayFeed;
  const transcriptText = transcript
    .map(e => {
      const t = new Date(e.ts).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
      return `[${t}] [${e.audioType.toUpperCase()}] ${e.text}`;
    })
    .join('\n');

  // Cap transcript to ~8000 chars to stay within token limits
  const cappedTranscript = transcriptText.length > 8000
    ? transcriptText.slice(0, 4000) + '\n\n[...middle of meeting omitted...]\n\n' + transcriptText.slice(-4000)
    : transcriptText;

  // ── LLM prompt ────────────────────────────────────────────────────────
  const systemPrompt = `You are a meticulous meeting analyst. You produce thorough, well-structured meeting summaries that serve as the definitive record of what happened. Reply with strict JSON only, no markdown fences.`;

  const userPrompt = `Analyze this meeting and produce a comprehensive summary.

Meeting date: ${dateStr}
Meeting time: ${timeStr}
Duration: ${durationMin} minutes (${state.segmentCount} speech segments)
Participants: ${participantNames || '(unknown)'}
${contextLine}
Live overview log (timestamped):
${overviewText || '(no overview captured)'}

Action items captured during meeting:
${actionText || '(none)'}

Final topic: ${state.summaryTree.topic.text || '(none)'}

Full transcript (timestamped):
${cappedTranscript}

Produce JSON with these fields:
{
  "title": "5-9 word title capturing the meeting's main purpose or outcome",
  "summary": "A thorough meeting summary as plain text. Structure it as follows:

WHAT HAPPENED: Walk through the meeting chronologically. What was discussed, in what order? Reference specific topics by name.

DECISIONS MADE: List every decision that was made, no matter how small. Who decided what? Include any deadlines, dates, or commitments mentioned. If someone said 'let's do X by Friday' or 'we agreed on Y', capture it here.

KEY POINTS: Important information shared, concerns raised, or insights offered. Include specific names of people, projects, numbers, or dates mentioned.

OPEN ITEMS: Anything left unresolved — questions that weren't answered, topics that need follow-up, disagreements that weren't settled.

Be specific and detailed. Use actual names, dates, and facts from the transcript. Never say 'various topics were discussed' — say exactly what was discussed. This summary should allow someone who missed the meeting to know exactly what happened."
}`;

  // ── Call LLM ──────────────────────────────────────────────────────────
  try {
    const response = await callLLM({
      tier: 'medium',
      prompt: userPrompt,
      systemPrompt,
      options: { max_tokens: 1200 },
    });

    const { data } = parseLLMJSON(response.content);
    const title =
      data && typeof data === 'object' && typeof (data as Record<string, unknown>).title === 'string'
        ? ((data as Record<string, unknown>).title as string).trim()
        : '';
    const summary =
      data && typeof data === 'object' && typeof (data as Record<string, unknown>).summary === 'string'
        ? ((data as Record<string, unknown>).summary as string).trim()
        : '';

    if (!title && !summary) return state;

    // Return state with title + summary — caller handles persistence.
    // Do NOT call saveMeetingState here: the active record was already transitioned to
    // 'archive' by archiveCurrentMeeting, so upsert would create a phantom active row.
    return {
      ...state,
      title: title || state.title,
      summary: summary || state.summary,
    };
  } catch (error) {
    console.error('[MeetingTranscription] End-of-meeting summary failed:', error);
    return state;
  }
}

/**
 * Patch the summary of an already-archived meeting by id.
 * Called after the end-of-meeting LLM — archive was already saved.
 */
export async function updateArchivedMeetingSummary(
  meetingId: string,
  title: string,
  summary: string
): Promise<ArchivedMeeting[]> {
  const rows = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, MAX_ARCHIVE, MEETING_SUBTYPE_ARCHIVE);
  for (const row of rows) {
    const parsed = ArchivedMeetingSchema.safeParse(row.contentParsed);
    if (parsed.success && parsed.data.id === meetingId) {
      await widgetRecordStore.update(row.id, {
        content: { ...parsed.data, title, summary },
        title,
      });
      break;
    }
  }
  return loadArchivedMeetings();
}
