/**
 * Meeting Transcription Process
 *
 * PARADIGM: CAPTURE + ONE-SHOT ANALYSIS ──────────────────────────────────────
 * During a meeting, this module only manages state (types, persistence, archive).
 * NO LLM calls happen while the meeting is active — the user stays focused on
 * the meeting without distraction from incremental analysis.
 *
 * When the meeting ends, generateMeetingEndSummary() fires ONCE to produce a
 * comprehensive title + summary. If the Chrome extension is available it routes
 * through ChatGPT, otherwise falls back to the LLM API.
 *
 * FOCUS CONTEXT: OUT-OF-APP primarily.
 * Data comes from the native app's system audio (remote participants via
 * Zoom/Meet/Teams) and mic audio (local user), streamed via WebSocket.
 * The user is typically in another app while this runs.
 *
 * This module does NOT call processInput() / the core processor. Completed
 * meeting data is stored in DuckDB via widgetRecordStore, not the conversations
 * table.
 *
 * GAP — INTEGRATION WITH WORKING MEMORY:
 *   Live meeting segments are never fed into WorkingMemory (which only reads
 *   the conversations DB). This means the core processor's entity/topic/memory
 *   extraction is not enriched by live meeting content in real time.
 *   Future: after a meeting ends, push the full transcript through processInput()
 *   so entities, topics, and memories get extracted and persist cross-session.
 * ─────────────────────────────────────────────────────────────────────────────
 */

import { z } from 'zod';
import { generateText } from 'ai';
import { models } from '../../../services/aiProviders';
import { parseLLMJSON } from '../../../program/utils/jsonUtils';
import { profileStorage } from '../../../lib/profileStorage';
import { widgetRecordStore } from '../../../graph/stores/widgetRecordStore';
import { rambleExt } from '../../../modules/chrome-extension';

// ============================================================================
// Constants
// ============================================================================

// Settings stay in profileStorage — they are user preferences, not LLM-generated data
export const SETTINGS_STORAGE_KEY = 'meeting-transcription:settings';

// DuckDB widget type / subtype constants
const MEETING_WIDGET_TYPE = 'meeting';
const MEETING_SUBTYPE_ACTIVE = 'active';
const MEETING_SUBTYPE_ARCHIVE = 'archive';


const MAX_ARCHIVE = 50;

/** Gap in ms after which a new recording-started is treated as a new meeting */
export const NEW_MEETING_GAP_MS = 3 * 60 * 1000;

// ============================================================================
// Types
// ============================================================================

export interface SummaryLevel {
  text: string;
  /** Iconify icon name generated by LLM, e.g. "mdi:target" */
  icon: string;
  updatedAt: number;
}

export interface SummaryTree {
  /** Mirrors the latest overviewItem text — kept for archive/display compat */
  overall: SummaryLevel;
  /** Current major topic / phase. Full rewrite when discussion shifts. */
  topic: SummaryLevel;
  /** Latest exchange right now. Always updated. */
  now: SummaryLevel;
}

/** One bullet in the additive overview log. Appended, never deleted mid-meeting. */
export interface OverviewItem {
  text: string;
  ts: number;
}

export interface ActionItem {
  id: string;
  text: string;
  /** Inferred owner — participant name, "you", or undefined if unknown */
  owner?: string;
  /** Inferred deadline if mentioned, e.g. "by Friday" */
  deadline?: string;
  ts: number;
  done: boolean;
}

/** 'tense' = rising conflict/disagreement; 'negative' = clear frustration/anger */
export type SentimentLevel = 'neutral' | 'positive' | 'tense' | 'negative';

export interface Participant {
  name: string;
  audioType: 'mic' | 'system';
  firstSeenAt: number;
}

export interface TalkTime {
  micMs: number;
  systemMs: number;
}

/** A ~2s speaker-check within a single transcription segment */
export interface SpeakerTimelineEntry {
  timestampMs: number;
  speakerIndex: number;
  durationMs: number;
}

export interface FeedEntry {
  id: string;
  text: string;
  audioType: 'mic' | 'system';
  ts: number;
  /** Speaker index from native diarization (0, 1, 2...). Undefined when not available. */
  speakerIndex?: number;
  /** Per-~2s speaker attribution within this segment. Null/absent in solo mode. */
  speakerTimeline?: SpeakerTimelineEntry[];
}

export interface HistorySegment {
  text: string;
  audioType: 'mic' | 'system';
  ts: number;
  speakerIndex?: number;
}

export interface MeetingSettings {
  userName: string;
  meetingContext: string;
}

export interface MeetingState {
  displayFeed: FeedEntry[];
  /** Complete transcript — never truncated (cap 2000). Used for archiving & export. */
  fullFeed: FeedEntry[];
  history: HistorySegment[];
  summaryTree: SummaryTree;
  overviewItems: OverviewItem[];
  actionItems: ActionItem[];
  participants: Participant[];
  talkTime: TalkTime;
  sentiment: SentimentLevel;
  lastLLMCallAt: number;
  lastUpdatedAt: number;
  llmDurationMs: number;
  segmentCount: number;
  startedAt: number;
  /** Auto-generated meeting title (produced by end-of-meeting LLM call) */
  title: string;
  /** Detailed end-of-meeting summary — decisions, outcomes, key discussion points */
  summary: string;
  /** User-assigned speaker names keyed by "mic:0", "sys:1" etc. — per meeting */
  speakerNames: Record<string, string>;
}

export interface ArchivedMeeting {
  id: string;
  startedAt: number;
  endedAt: number;
  summaryTree: SummaryTree;
  overviewItems: OverviewItem[];
  actionItems: ActionItem[];
  participants: Participant[];
  talkTime: TalkTime;
  displayFeed: FeedEntry[];
  /** Complete transcript — never truncated (cap 2000). Used for export. */
  fullFeed: FeedEntry[];
  history: HistorySegment[];
  segmentCount: number;
  /** Auto-generated meeting title (produced by end-of-meeting LLM call) */
  title: string;
  /** Detailed end-of-meeting summary — decisions, outcomes, key discussion points */
  summary: string;
  /** User-assigned speaker names keyed by "mic:0", "sys:1" etc. — per meeting */
  speakerNames: Record<string, string>;
}

// ============================================================================
// Zod schemas
// ============================================================================

const SummaryLevelSchema = z.object({
  text: z.string(),
  icon: z.string(),
  updatedAt: z.number(),
});

const SummaryTreeSchema = z.object({
  overall: SummaryLevelSchema,
  topic: SummaryLevelSchema,
  now: SummaryLevelSchema,
});

const SpeakerTimelineEntrySchema = z.object({
  timestampMs: z.number(),
  speakerIndex: z.number(),
  durationMs: z.number(),
});

const FeedEntrySchema = z.object({
  id: z.string(),
  text: z.string(),
  audioType: z.enum(['mic', 'system']),
  ts: z.number(),
  speakerIndex: z.number().optional(),
  speakerTimeline: z.array(SpeakerTimelineEntrySchema).optional(),
});

const HistorySegmentSchema = z.object({
  text: z.string(),
  audioType: z.enum(['mic', 'system']),
  ts: z.number(),
  speakerIndex: z.number().optional(),
});

const OverviewItemSchema = z.object({
  text: z.string(),
  ts: z.number(),
});

const ActionItemSchema = z.object({
  id: z.string(),
  text: z.string(),
  owner: z.string().optional(),
  deadline: z.string().optional(),
  ts: z.number(),
  done: z.boolean(),
});

const ParticipantSchema = z.object({
  name: z.string(),
  audioType: z.enum(['mic', 'system']),
  firstSeenAt: z.number(),
});

const TalkTimeSchema = z.object({
  micMs: z.number(),
  systemMs: z.number(),
});

const SentimentLevelSchema = z.enum(['neutral', 'positive', 'tense', 'negative']);

const MeetingStateSchema = z.object({
  displayFeed: z.array(FeedEntrySchema),
  fullFeed: z.array(FeedEntrySchema).default([]),
  history: z.array(HistorySegmentSchema),
  summaryTree: SummaryTreeSchema,
  overviewItems: z.array(OverviewItemSchema),
  actionItems: z.array(ActionItemSchema),
  participants: z.array(ParticipantSchema),
  talkTime: TalkTimeSchema,
  sentiment: SentimentLevelSchema,
  lastLLMCallAt: z.number(),
  lastUpdatedAt: z.number(),
  llmDurationMs: z.number(),
  segmentCount: z.number(),
  startedAt: z.number(),
  // default('') so existing stored data without this field migrates instead of being wiped
  title: z.string().default(''),
  summary: z.string().default(''),
  speakerNames: z.record(z.string(), z.string()).default({}),
});

const ArchivedMeetingSchema = z.object({
  id: z.string(),
  startedAt: z.number(),
  endedAt: z.number(),
  summaryTree: SummaryTreeSchema,
  overviewItems: z.array(OverviewItemSchema),
  actionItems: z.array(ActionItemSchema),
  participants: z.array(ParticipantSchema),
  talkTime: TalkTimeSchema,
  displayFeed: z.array(FeedEntrySchema),
  fullFeed: z.array(FeedEntrySchema).default([]),
  history: z.array(HistorySegmentSchema),
  segmentCount: z.number(),
  // default('') so existing archived meetings without this field migrate instead of being wiped
  title: z.string().default(''),
  summary: z.string().default(''),
  speakerNames: z.record(z.string(), z.string()).default({}),
});

const MeetingSettingsSchema = z.object({
  userName: z.string(),
  meetingContext: z.string(),
});

// ============================================================================
// Storage — meeting state + archive → DuckDB; settings → profileStorage
// ============================================================================

/**
 * Save active meeting state (fire-and-forget upsert — never throws).
 * Keeps sync signature so Widget.tsx call sites don't need to change.
 */
export function saveMeetingState(state: MeetingState): void {
  widgetRecordStore.upsert(MEETING_WIDGET_TYPE, MEETING_SUBTYPE_ACTIVE, {
    content: state,
    title: state.title || 'Active Meeting',
  }).catch(e => console.warn('[MeetingTranscription] Failed to save state:', e));
}

/**
 * Load active meeting state from DuckDB with Zod validation.
 */
export async function loadMeetingState(): Promise<MeetingState | null> {
  try {
    // Check how many active records exist (should be 0 or 1)
    const allActive = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, 100, MEETING_SUBTYPE_ACTIVE);
    console.log('[Load] active records in DB:', allActive.length);

    const record = allActive[0] ?? null;
    if (!record) return null;

    const result = MeetingStateSchema.safeParse(record.contentParsed);
    if (!result.success) {
      console.warn('[MeetingTranscription] State schema changed — resetting:', result.error.issues);
      return null;
    }
    console.log('[Load] loaded active state — segments:', result.data.segmentCount, 'startedAt:', result.data.startedAt);
    return result.data;
  } catch (error) {
    console.warn('[MeetingTranscription] Failed to load state:', error);
    return null;
  }
}

/**
 * Clear the active meeting state (fire-and-forget — never throws).
 */
export function clearMeetingState(): void {
  widgetRecordStore.getLatest(MEETING_WIDGET_TYPE, MEETING_SUBTYPE_ACTIVE)
    .then(record => record ? widgetRecordStore.delete(record.id) : undefined)
    .catch(e => console.warn('[MeetingTranscription] Failed to clear state:', e));
}

/**
 * Load archived meetings from DuckDB (up to MAX_ARCHIVE, most recent first).
 */
export async function loadArchivedMeetings(): Promise<ArchivedMeeting[]> {
  try {
    const rows = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, MAX_ARCHIVE, MEETING_SUBTYPE_ARCHIVE);
    const seen = new Set<string>();
    const meetings: ArchivedMeeting[] = [];
    for (const row of rows) {
      const result = ArchivedMeetingSchema.safeParse(row.contentParsed);
      if (result.success && !seen.has(result.data.id)) {
        seen.add(result.data.id);
        meetings.push(result.data);
      }
    }
    return meetings;
  } catch {
    return [];
  }
}

/**
 * Archive the current meeting.
 * Transitions the active row to 'archive' subtype (or creates a new archive row if missing).
 * Returns the updated list of archived meetings.
 */
export async function archiveCurrentMeeting(state: MeetingState): Promise<ArchivedMeeting[]> {
  if (state.segmentCount === 0) return loadArchivedMeetings();

  const archived: ArchivedMeeting = {
    id: `meeting-${state.startedAt}`,
    startedAt: state.startedAt,
    endedAt: Date.now(),
    summaryTree: state.summaryTree,
    overviewItems: state.overviewItems,
    actionItems: state.actionItems,
    participants: state.participants,
    talkTime: state.talkTime,
    displayFeed: state.displayFeed,
    fullFeed: state.fullFeed,
    history: state.history,
    segmentCount: state.segmentCount,
    title: state.title,
    summary: state.summary,
    speakerNames: state.speakerNames,
  };

  // Get ALL active records — fire-and-forget saveMeetingState can create duplicates
  // via the non-atomic upsert race. We must transition/clean ALL of them.
  const allActive = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, 100, MEETING_SUBTYPE_ACTIVE);
  console.log('[Archive] active records found:', allActive.length);

  if (allActive.length > 0) {
    // Transition the first (latest) to archive with the meeting data
    await widgetRecordStore.update(allActive[0].id, {
      content: archived,
      subtype: MEETING_SUBTYPE_ARCHIVE,
      title: archived.title || undefined,
    });
    // Delete any stale duplicate active records
    for (let i = 1; i < allActive.length; i++) {
      console.log('[Archive] deleting stale active record:', allActive[i].id);
      await widgetRecordStore.delete(allActive[i].id);
    }
  } else {
    // No active row exists — create a new archive row directly
    await widgetRecordStore.create({
      type: MEETING_WIDGET_TYPE,
      subtype: MEETING_SUBTYPE_ARCHIVE,
      content: archived,
      title: archived.title || undefined,
      createdAt: archived.startedAt,
    });
  }

  return loadArchivedMeetings();
}

/**
 * Patch the title of an already-archived meeting by id.
 * Called after the end-of-meeting LLM title generation — archive was already saved.
 */
export async function updateArchivedMeetingTitle(meetingId: string, title: string): Promise<ArchivedMeeting[]> {
  // Find the archive row whose content has the matching id
  const rows = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, MAX_ARCHIVE, MEETING_SUBTYPE_ARCHIVE);
  for (const row of rows) {
    const parsed = ArchivedMeetingSchema.safeParse(row.contentParsed);
    if (parsed.success && parsed.data.id === meetingId) {
      await widgetRecordStore.update(row.id, {
        content: { ...parsed.data, title },
        title,
      });
      break;
    }
  }
  return loadArchivedMeetings();
}

export function loadMeetingSettings(): MeetingSettings {
  try {
    const raw = profileStorage.getJSON<unknown>(SETTINGS_STORAGE_KEY);
    if (raw == null) return { userName: '', meetingContext: '' };
    const result = MeetingSettingsSchema.safeParse(raw);
    return result.success ? result.data : { userName: '', meetingContext: '' };
  } catch {
    return { userName: '', meetingContext: '' };
  }
}

export function saveMeetingSettings(settings: MeetingSettings): void {
  try {
    profileStorage.setJSON(SETTINGS_STORAGE_KEY, settings);
  } catch (error) {
    console.warn('[MeetingTranscription] Failed to save settings:', error);
  }
}

// ============================================================================
// Initial state
// ============================================================================

export function createInitialMeetingState(): MeetingState {
  return {
    displayFeed: [],
    fullFeed: [],
    history: [],
    summaryTree: {
      overall: { text: '', icon: 'mdi:flag-outline', updatedAt: 0 },
      topic:   { text: '', icon: 'mdi:comment-multiple-outline', updatedAt: 0 },
      now:     { text: '', icon: 'mdi:lightning-bolt-outline', updatedAt: 0 },
    },
    overviewItems: [],
    actionItems: [],
    participants: [],
    talkTime: { micMs: 0, systemMs: 0 },
    sentiment: 'neutral',
    lastLLMCallAt: 0,
    lastUpdatedAt: Date.now(),
    llmDurationMs: 0,
    segmentCount: 0,
    startedAt: Date.now(),
    title: '',
    summary: '',
    speakerNames: {},
  };
}

// ============================================================================
// End-of-meeting summary
//
// Single LLM call fired once when recording ends.
// This is the designated slot for ALL future end-of-meeting features.
// Currently generates: title + comprehensive summary.
// Future: decisions log, key numbers, follow-up email draft, etc.
// ============================================================================

/**
 * Generate end-of-meeting title + detailed summary.
 *
 * This is the ONE post-meeting LLM call. Uses medium tier — meeting is over,
 * latency doesn't matter, quality does. Receives full transcript + live
 * overview + action items and produces a thorough meeting record.
 *
 * The caller (Widget.tsx) handles persisting title + summary to the archive.
 */
export async function generateMeetingEndSummary(
  state: MeetingState,
  settings: MeetingSettings
): Promise<MeetingState> {
  if (state.segmentCount === 0) return state;

  // ── Assemble meeting context ──────────────────────────────────────────
  const meetingDate = new Date(state.startedAt);
  const dateStr = meetingDate.toLocaleDateString('en-US', {
    weekday: 'long', year: 'numeric', month: 'long', day: 'numeric',
  });
  const timeStr = meetingDate.toLocaleTimeString('en-US', {
    hour: '2-digit', minute: '2-digit',
  });
  const durationMin = Math.round((Date.now() - state.startedAt) / 60000);

  const overviewText = state.overviewItems.map((item, i) => {
    const itemTime = new Date(item.ts).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
    return `${i + 1}. [${itemTime}] ${item.text}`;
  }).join('\n');

  const actionText = state.actionItems
    .map(a => `- ${a.done ? '[DONE] ' : ''}${a.text}${a.owner ? ` [${a.owner}]` : ''}${a.deadline ? ` — due: ${a.deadline}` : ''}`)
    .join('\n');

  const contextLine = settings.meetingContext ? `Meeting context: ${settings.meetingContext}\n` : '';
  const participantNames = state.participants.map(p => `${p.name} (${p.audioType})`).join(', ');

  // Build transcript with timestamps — use speaker labels when available
  const transcript = state.fullFeed.length > 0 ? state.fullFeed : state.displayFeed;
  const transcriptText = transcript
    .map(e => {
      const t = new Date(e.ts).toLocaleTimeString('en-US', { hour: '2-digit', minute: '2-digit' });
      const speakerKey = e.speakerIndex != null ? `${e.audioType === 'mic' ? 'mic' : 'sys'}:${e.speakerIndex}` : null;
      const label = speakerKey
        ? (state.speakerNames[speakerKey] || `${e.audioType.toUpperCase()} Speaker ${e.speakerIndex}`)
        : e.audioType.toUpperCase();
      return `[${t}] [${label}] ${e.text}`;
    })
    .join('\n');

  // Cap transcript to ~8000 chars to stay within token limits
  const cappedTranscript = transcriptText.length > 8000
    ? transcriptText.slice(0, 4000) + '\n\n[...middle of meeting omitted...]\n\n' + transcriptText.slice(-4000)
    : transcriptText;

  // ── LLM prompt ────────────────────────────────────────────────────────
  const systemPrompt = `You are a meticulous meeting analyst. You produce thorough, well-structured meeting summaries that serve as the definitive record of what happened. Reply with strict JSON only, no markdown fences.`;

  const userPrompt = `Analyze this meeting and produce a comprehensive summary.

Meeting date: ${dateStr}
Meeting time: ${timeStr}
Duration: ${durationMin} minutes (${state.segmentCount} speech segments)
Participants: ${participantNames || '(unknown)'}
${contextLine}
Live overview log (timestamped):
${overviewText || '(no overview captured)'}

Action items captured during meeting:
${actionText || '(none)'}

Final topic: ${state.summaryTree.topic.text || '(none)'}

Full transcript (timestamped):
${cappedTranscript}

Produce JSON with these fields:
{
  "title": "5-9 word title capturing the meeting's main purpose or outcome",
  "summary": "A thorough meeting summary as plain text. Structure it as follows:

WHAT HAPPENED: Walk through the meeting chronologically. What was discussed, in what order? Reference specific topics by name.

DECISIONS MADE: List every decision that was made, no matter how small. Who decided what? Include any deadlines, dates, or commitments mentioned. If someone said 'let's do X by Friday' or 'we agreed on Y', capture it here.

KEY POINTS: Important information shared, concerns raised, or insights offered. Include specific names of people, projects, numbers, or dates mentioned.

OPEN ITEMS: Anything left unresolved — questions that weren't answered, topics that need follow-up, disagreements that weren't settled.

Be specific and detailed. Use actual names, dates, and facts from the transcript. Never say 'various topics were discussed' — say exactly what was discussed. This summary should allow someone who missed the meeting to know exactly what happened."
}`;

  // ── Call LLM ──────────────────────────────────────────────────────────
  // Prefer ChatGPT via Chrome extension when available, otherwise fall back
  // to our own LLM API.
  try {
    let rawContent: string;

    if (rambleExt.isAvailable) {
      console.log('[MeetingTranscription] Extension available → sending to ChatGPT');
      const fullPrompt = `${systemPrompt}\n\n${userPrompt}`;
      const response = await rambleExt.aiRaw({ target: 'chatgpt', prompt: fullPrompt });
      rawContent = response.answer;
    } else {
      console.log('[MeetingTranscription] Extension unavailable → using LLM API');
      const { text: llmText } = await generateText({
        model: models.medium,
        system: systemPrompt,
        prompt: userPrompt,
      });
      rawContent = llmText;
    }

    const { data } = parseLLMJSON(rawContent);
    const title =
      data && typeof data === 'object' && typeof (data as Record<string, unknown>).title === 'string'
        ? ((data as Record<string, unknown>).title as string).trim()
        : '';
    const summary =
      data && typeof data === 'object' && typeof (data as Record<string, unknown>).summary === 'string'
        ? ((data as Record<string, unknown>).summary as string).trim()
        : '';

    if (!title && !summary) return state;

    // Return state with title + summary — caller handles persistence.
    // Do NOT call saveMeetingState here: the active record was already transitioned to
    // 'archive' by archiveCurrentMeeting, so upsert would create a phantom active row.
    return {
      ...state,
      title: title || state.title,
      summary: summary || state.summary,
    };
  } catch (error) {
    console.error('[MeetingTranscription] End-of-meeting summary failed:', error);
    return state;
  }
}

/**
 * Patch the summary of an already-archived meeting by id.
 * Called after the end-of-meeting LLM — archive was already saved.
 */
export async function updateArchivedMeetingSummary(
  meetingId: string,
  title: string,
  summary: string
): Promise<ArchivedMeeting[]> {
  const rows = await widgetRecordStore.getRecent(MEETING_WIDGET_TYPE, MAX_ARCHIVE, MEETING_SUBTYPE_ARCHIVE);
  for (const row of rows) {
    const parsed = ArchivedMeetingSchema.safeParse(row.contentParsed);
    if (parsed.success && parsed.data.id === meetingId) {
      await widgetRecordStore.update(row.id, {
        content: { ...parsed.data, title, summary },
        title,
      });
      break;
    }
  }
  return loadArchivedMeetings();
}
